#define STRING_1 L"Raiden Shogun wish simulation"
#define STRING_2 "Checking for updates, please wait."
#define STRING_3 "Write your name:"
#define STRING_4 "Hello "
#define STRING_5 ",you wished "
#define STRING_6 " times."
#define STRING_7 "You take "
#define STRING_8 " primogems."
#define STRING_9 "Amount to "
#define STRING_10 " yuan or "
#define STRING_11 " of 648."
#define STRING_12 "Now,you have "
#define STRING_13 " of "
#define STRING_14 "."
#define STRING_15 "You skew "
#define STRING_16 " times."
#define STRING_17 "1.wish*1  2.wish*10  3.setting  4.delete data and exit  5.save data and exit"
#define STRING_18 "Restore Default?(y/n)\n"
#define STRING_19 "Window size (column):"
#define STRING_20 "Window size (rows):"
#define STRING_21 "Update (1/0)"
#define STRING_22 "Invalid! Re input:"
#define STRING_23 "Please restart to update.\n"